### ISSUE TITLE
Per release specialty tests for Android Ads on ARM for 1.1.0

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1768]
- [x] Implement IsNotificationsAvailable. ([#1518](https://github.com/brave/browser-android-tabs/issues/1518))
 - [x] Implement Brave Ads have arrived! On-Boarding UI. ([#1523](https://github.com/brave/browser-android-tabs/issues/1523))
 - [x] Turn off rewards shows coming soon text for ads. ([#1585](https://github.com/brave/browser-android-tabs/issues/1585))
 - [x] Ads earning and ad view count momentarily flashes when pull down reload the ads setting page. ([#1610](https://github.com/brave/browser-android-tabs/issues/1610))
 - [x] Badge count should not be shown for Ad notifications. ([#1611](https://github.com/brave/browser-android-tabs/issues/1611))
 - [x] Staging flag should set ads to staging as well. Follow upto #1540. ([#1626](https://github.com/brave/browser-android-tabs/issues/1626))
 - [x] Default Browser Notification Adjustment. ([#1677](https://github.com/brave/browser-android-tabs/issues/1677))
 - [x] Brave Rewards are Here Notification Removal. ([#1678](https://github.com/brave/browser-android-tabs/issues/1678))
 - [x] Update timings on Brave Ads here modal for new users. ([#1679](https://github.com/brave/browser-android-tabs/issues/1679))
 - [x] Badge notification isn't removed even after user opts into Brave Ads. ([#1687](https://github.com/brave/browser-android-tabs/issues/1687))
 - [x] Upgrade profile shows incorrect onboarding notification message. ([#1688](https://github.com/brave/browser-android-tabs/issues/1688))
 - [x] Brave rewards/ads modals. ([#1689](https://github.com/brave/browser-android-tabs/issues/1689))
 - [x] Enable rewards doesn't auto enable ads. ([#1694](https://github.com/brave/browser-android-tabs/issues/1694))
 - [x] I'M IN on upgrade doesn't enable rewards . ([#1700](https://github.com/brave/browser-android-tabs/issues/1700))
 - [x] BAT red notification badge for new users. ([#1724](https://github.com/brave/browser-android-tabs/issues/1724))
 - [x] Incorrect `Next Payment Date` display in Ads panel. ([#1725](https://github.com/brave/browser-android-tabs/issues/1725))
 - [x] `Next Payment Date` field is empty, delay in fetching the date field. ([#1727](https://github.com/brave/browser-android-tabs/issues/1727))
 - [x] Sorry! Ads not supported message is displayed in brave://rewards page for ads supported region. ([#1728](https://github.com/brave/browser-android-tabs/issues/1728))
 - [x] Implement mobile ad onboarding. ([#1729](https://github.com/brave/browser-android-tabs/issues/1729))
 - [x] Inconsistent DD/MM/YYYY format in auto contribute settings. ([#1732](https://github.com/brave/browser-android-tabs/issues/1732))
 - [x] Ads count isn't updated immediately after notification is done. ([#1736](https://github.com/brave/browser-android-tabs/issues/1736))
 - [x] Default Browser Notification Text Changes. ([#1742](https://github.com/brave/browser-android-tabs/issues/1742))

**Comment by srirambv** [comment]
Closing as all listed issues are verified
