### ISSUE TITLE
Manual test run on Android Tab  for 1.3.0

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1990]
## Per release specialty tests
 - [x] Closing all tabs closes browser (default switch). ([#1716](https://github.com/brave/browser-android-tabs/issues/1716))
 - [x] Turn off haptics for Brave Ads Notifications. ([#1866](https://github.com/brave/browser-android-tabs/issues/1866))
 - [ ] Update Android Ads Policy. ([#1913](https://github.com/brave/browser-android-tabs/issues/1913))
 - [x] Replay Welcome Tour back button. ([#1972](https://github.com/brave/browser-android-tabs/issues/1972))
 - [ ] Move "Close last tab closes Brave" in settings. ([#1973](https://github.com/brave/browser-android-tabs/issues/1973))
 - [x] Close all tabs settings gets changed when browser is relaunced. ([#1976](https://github.com/brave/browser-android-tabs/issues/1976))
 - [x] Sync QR code is missing warning text . ([#1977](https://github.com/brave/browser-android-tabs/issues/1977))
 - [x] Browser crash when home page option is turned off . ([#1981](https://github.com/brave/browser-android-tabs/issues/1981))
 - [x] Verified icon and pub name needs padding in between. ([#1983](https://github.com/brave/browser-android-tabs/issues/1983))

## Visual look

- [x] Make sure there after every merge
  - [x] No Chrome/Chromium words appear on normal or private tabs
  - [x] No Chrome/Chromium icons are shown in normal or private tabs

## Data
Pre-Requisite: Put previous build shortcut on home screen. Also have several sites 'Added to home screen' (from 3 dots menu) and then upgrade to new build
- [x] Verify that data from the previous build appears in the updated build as expected (bookmarks, etc)
- [x] Verify that the cookies from the previous build are preserved after upgrade
- [x] Verify shortcut is still available on home screen after upgrade
- [x] Verify sites added to home screen are still visible and able to be used after upgrade
- [x] Verify sync chain created in previous version is still retained on upgrade
- [x] Verify settings changes done in previous version is still retained on upgrade
## Context menus

- [x] Make sure context menu items in the URL bar work
- [x] Make sure context menu items on content work with no selected text
- [x] Make sure context menu items on content work with selected text
- [x] Make sure context menu items on content work inside an editable control (input, textarea, or contenteditable)

## Developer Tools

- [x] Verify you are able to inspect sublinks via dev tools

## Sync

- [x] Verify you are able to join sync chain by scanning the QR code
- [x] Verify you are able to join sync chain using code words
- [x] Verify you are able to create a sycn chain on the device and add other devices to the chain via QR code/Code words
- [x] Verify that bookmarks from other devices on the chain show up on the mobile device after sync completes
- [x] Verify newly created bookmarks gets sync'd to all devices on the sync chain
- [x] Verify existing bookmarks before joining sync chain also gets sync'd to all devices on the sync chain
- [x] Verify sync works on a upgrade profile and new bookmarks added post upgrade sync's across devices on the chain
- [x] Verify add a bookmark on custom tab gets sync'd across all devices in the chain
- [x] Verify you are able to create a standalone sync chain with one device

## Bravery settings

- [x] Check that HTTPS Everywhere works by loading http://https-everywhere.badssl.com/
- [x] Turning HTTPS Everywhere off and shields off both disable the redirect to https://https-everywhere.badssl.com/
- [x] Check that toggling to blocking and allow ads works as expected
- [x] Verify that clicking through a cert error in https://badssl.com/ works
- [x] Visit https://brianbondy.com/ and then turn on script blocking, nothing should load. Allow it from the script blocking UI in the URL bar and it should work.
- [x] Verify that about:preferences default Bravery settings take effect on pages with no site settings
- [x] Verify that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/7/ when 3rd party cookies are blocked
### Fingerprint Tests
  - [x] Visit https://browserleaks.com/webrtc, ensure 2 blocked items are listed in shields
  - [x] Verify that https://diafygi.github.io/webrtc-ips/ doesn't leak IP address when `Block all fingerprinting protection` is on

## Content Tests

- [x] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Verify that context menus work in the new twitter tab
- [x] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved. Make sure the saved password is auto-populated when you visit the site again
- [x] Open a github issue and type some misspellings, make sure they aren't autocorrected
- [x] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works
- [x] Verify that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run)

## Top sites view

- [x] Long-press on top sites to get to deletion mode, and delete a top site (note this will stop that site from showing up again on top sites, so you may not want to do this a site you want to keep there)

## Background

- [x] Start loading a page, background the app, wait > 5 sec, then bring to front, ensure splash screen is not shown

## Session storage

- [x] Verify that tabs restore when closed, including active tab
